### PR TITLE
add detection for blocking channels and ensure goroutine dies

### PR DESCRIPTION
**Pull request by kcollasarundell**
stream.stream has a blocking condition when trying to push onto the
error channel. this channel can get closed by other goroutines and
will cause this goroutine to leak.

by passing to a default case we can drop the error message when we are
unable to return it and move to reconnect logic.

We also add in detection for stream cancellation from higher calling
goroutines in preparation for shutdown logic to be added

### CODE REVIEW

**Comment by delfick** [comment]
awesome

**Comment by kcollasarundell** [comment]
@smarthall says go as well

**Comment by tatey** [comment]
Nice one. You should try getting these merged upstream 😄

**Comment by kcollasarundell** [comment]
I intend to go through the upstream repo and merge most of these changes back. hunt down the channel blocking changes first and then add context methods.

**Pull request merged**
